### PR TITLE
Skip disabled constraints when visiting model; Fixes #173

### LINKED ISSUE #173: Setting constraint_mode to False retains the previous range/bounds of the constraint
I was modifying the example in the ["Constraint Mode" section](https://fvutils.github.io/pyvsc/constraints.html#constraint-mode) and noticed that disabling the constraint via constraint_mode wasn't working. I tried both setting it to a constant (a == 0) and constraining it between two constants (a >= 0, a < 100). I assume this is b/c the calculated bounds is being used on a now unconstrained variable?

There are some "with item.randomize():" lines in the examples that have no following statement. Maybe I can go through some more examples and clean those up along the way and submit something.

Using git pyvsc: commit 743b6d3c3376dfa15feab91bfe454f5ee5a53eac tag: v0.8.2

Constraint Mode example but constraining a to a single constant value:
```python
#!/usr/bin/env python3

import vsc

@vsc.randobj
class my_item(object):

    def __init__(self):
        self.a = vsc.rand_bit_t(8)
        self.b = vsc.rand_bit_t(8)
    
    @vsc.constraint
    def valid_ab_c(self):
       # self.a < self.b
       self.a == 42

item = my_item()
debug = 0

# Always generate valid values
for i in range(10):
   item.randomize(debug=debug)
   print(True, item.a, item.b)

item.valid_ab_c.constraint_mode(False)

# Allow invalid values
for i in range(10):
   item.randomize(debug=debug)
   print(False, item.a, item.b)
```

### PR DESCRIPTION
**Pull request by alwilson**
Traced the bounds processing to ModelVisitor and added a constraint enabled check.

Added a unittest that passes with this commit.

### CODE REVIEW

**Comment by mballance** [comment]
Hi @alwilson, thanks for taking the time to dig into this issue! If I understand correctly from issue #173, it seems that the core problem is that the bounds visitor isn't ignoring disabled constraints. If that is the case, I would recommend overriding the visit_constraint_block method from ModelVisitor (see below) in the bounds visitor class and only visit the base implementation if the constraint is enabled.
https://github.com/fvutils/pyvsc/blob/743b6d3c3376dfa15feab91bfe454f5ee5a53eac/src/vsc/model/model_visitor.py#L106-L107

It should look something like:

```python3
    def visit_constraint_block(self, c : ConstraintBlockModel):
        if c.enabled:
            super().visit_constraint_block(c)
```

This will allow other users of the ModelVisitor class to receive notifications of disabled and enabled constraint blocks, while blocking the bounds visitor from taking disabled constraints into account.

**Comment by alwilson** [comment]
Ah, reread your comment after going back. I need to play with git some more too. Haven't done much rebase/squash stuff from the command line before.

**Comment by mballance** [comment]
@alwilson, don't worry about squashing commits or rebasing -- this is a nice small change. If it were me, I'd just copy/paste the visit_constraint_block method over to the bounds visitor class, revert the changes in the model_visitor class, and call it it a day. Your call, though :-)

**Comment by alwilson** [comment]
Yeah, it does feel like a hole in my git knowledge... but I think even github will let you squash merge as well if you wanted. I recall seeing options for it before at least. Thanks for the feedback!

**Comment by mballance** [comment]
Many thanks, @alwilson!

**Pull request merged**
